services:
  postgres:
    image: postgres:16
    container_name: confirmare-postgres
    environment:
      POSTGRES_DB: confirmare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - confirmare_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: confirmare-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@confirmare.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  confirmare_postgres_data:
